#!/usr/bin/env bash
# Configures localhost and facebook.com to resolve to specific IP addresses

sed -e 's/^127\.0\.0\.1[[:space:]]*localhost/127.0.0.2 localhost/' \
    -e '/facebook\.com/d' /etc/hosts > /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
cat /tmp/hosts > /etc/hosts
